# This is a targets script generated by tar_script() and edited after that. This script makes a folder called "_targets", with meta data and files of targets inside it. 
library(targets)

# Define custom functions and other global objects.
get_event <- 
  function(corp_x, quant_x) {
    docvars(corp_x) %>% 
      tibble() %>% 
      # Number of tweets for each day. 
      group_by(year, month, date) %>% 
      summarise(tw_num = n()) %>% 
      ungroup() %>% 
      # Highlight the high-tweet-number date: compared with annual 90% quantile tweet number. 
      group_by(year) %>% 
      mutate(quant = quantile(tw_num, quant_x)) %>% 
      ungroup() %>% 
      filter(tw_num >= quant) %>% 
      arrange(year, date) %>% 
      mutate(
        date_backward = lag(date, 1), 
        date_forward = lead(date, 1), 
        date_diff_pre = date - date_backward, 
        date_diff_after = date_forward - date, 
        continue_condition = c(
          date_diff_pre == 1 | date_diff_after == 1 | 
            is.na(date_diff_pre) | is.na(date_diff_after)
        ), 
        # Make groups: every period of continue date is considered as one group. 
        change_condition = 
          c(date_diff_pre != 1 | is.na(date_diff_pre))
      ) %>% 
      mutate(grp = cumsum(change_condition)) %>% 
      group_by(grp) %>% 
      mutate(
        row_num = row_number(), 
        max_row_num = max(row_num)
      ) %>% 
      # Keep days of continue date of high-tweet-number >= 3 days. 
      filter(max_row_num >= 3) %>% 
      return()
  }

# Set target-specific options such as packages:
tar_option_set(packages = c(
  "dplyr", "tidyr", "quanteda", "quanteda.textstats", "quanteda.textplots",
  "stopwords", "LSX", "ggplot2", "ggraph", "patchwork", "igraph", "lubridate"
)) 

# List of target objects.
list(
  # get corpus based on tweet data in *.csv files
  tar_target(
    corp, 
    lapply(
      # Raw data from 2012 to 2021 are all complete year data; while data for 2022 is not complete. 
      list.files("data_raw/tweet_raw", full.names = TRUE), 
      function(x) {
        data.table::fread(x) %>% 
          tibble() %>% 
          # parse created_at of tweets to get year and month info
          mutate(
            date = as_date(JSTdate), 
            year = year(date), 
            month = month(date), 
            # Bug: The cost of the interaction actions? Do not include reply and like here? Reason: retweet and quote means broadcast the info again to other users. 
            retweet_quote_count = 
              public_metrics.retweet_count + public_metrics.quote_count
          ) %>% 
          select(
            id, date, year, month, author.id, text
          ) %>% 
          rename_with(~ gsub(".", "_", .x, fixed = TRUE))
      }
    ) %>% 
      do.call(rbind, .) %>% 
      corpus(text_field = "text")
  ), 
  # The event-identification: continue date with high-tweet-number. 
  tar_target(
    tw_high_90, 
    get_event(corp_x = corp, quant_x = 0.9)
  ), 
  tar_target(
    tw_high_85, 
    get_event(corp_x = corp, quant_x = 0.85)
  )
)
